# Generated by Django 5.0.1 on 2024-01-10 04:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=800)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modify', models.DateTimeField(auto_now=True)),
                ('closed_by', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('solution', models.TextField(blank=True, default=None, max_length=800, null=True)),
                ('status', models.CharField(choices=[('ABERTO', 'Em aberto'), ('ANDAMENTO', 'Em andamento'), ('CONCLUIDO', 'Concluído')], default='ABERTO', max_length=50)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['status'],
            },
        ),
    ]
