# Generated by Django 4.2.9 on 2024-01-10 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_ticket_closed_at_ticket_feedback_ticket_origin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='tags',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
