# Generated by Django 5.0.1 on 2024-01-10 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='concluded_tickets',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='device_ip',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='device_ip_log',
            field=models.TextField(blank=True, default=None, max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='device_os',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='in_progress_tickets',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='language_preference',
            field=models.CharField(choices=[('PT-BR', 'Português do Brasil'), ('PT-PT', 'Português de Portugal'), ('EN-US', 'Inglês'), ('ES-ES', 'Espanhol')], default='PT-BR', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notification_preference',
            field=models.CharField(choices=[('DESATIVADO', 'Desativado'), ('SITE', 'Site'), ('EMAIL', 'Email')], default='SITE', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='open_tickets',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='public_profile',
            field=models.BooleanField(default=False, max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='total_tickets',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='theme_preference',
            field=models.CharField(blank=True, choices=[('LIGHT', 'Modo Claro'), ('DARK', 'Modo Escuro'), ('AUTO', 'Automático')], default='LIGHT', max_length=20, null=True),
        ),
    ]
